/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_cassandra_io_erasurecode_NativeRSDecoder */

#ifndef _Included_org_apache_cassandra_io_erasurecode_NativeRSDecoder
#define _Included_org_apache_cassandra_io_erasurecode_NativeRSDecoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_cassandra_io_erasurecode_NativeRSDecoder
 * Method:    initImpl
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_apache_cassandra_io_erasurecode_NativeRSDecoder_initImpl
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_apache_cassandra_io_erasurecode_NativeRSDecoder
 * Method:    decodeImpl
 * Signature: ([Ljava/nio/ByteBuffer;[II[I[Ljava/nio/ByteBuffer;[I)V
 */
JNIEXPORT void JNICALL Java_org_apache_cassandra_io_erasurecode_NativeRSDecoder_decodeImpl
  (JNIEnv *, jobject, jobjectArray, jintArray, jint, jintArray, jobjectArray, jintArray);

/*
 * Class:     org_apache_cassandra_io_erasurecode_NativeRSDecoder
 * Method:    destroyImpl
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_apache_cassandra_io_erasurecode_NativeRSDecoder_destroyImpl
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
